### ISSUE TITLE
Some  problem about Semantic regularization

### ISSUE THREAD

**Issue by HalvesChen** [lxa9867/ImageFolder#1]
Hi, thanks your great job! I have some problem:
1. Have you ever compared the difference between distillation loss (MSE, COS) with clip loss? How much the clip loss eventually converges to have a good effect?

**Comment by lxa9867** [comment]
Hi, thanks for the interest.

We did not try distillation losses as they will force the output the same as DINO (which is not suitable for image generation tab.2). Compared to the vanilla distillation loss, relational distillation may be more suitable. 

Our clip loss converges to 0.000x eventually.

**Comment by HalvesChen** [comment]
Thanks for your reply, it's helpful~
One more question about codebook dimension set in the paper. As I understand it, due to the need to distill DINOV2 features, the regular codebook dimension settings (e.g. 8, 16, 32) may not be sufficient? But if a larger codebook dimension is set, it will lead to poorer reconstruction or codebook crash according to previous conclusions.

**Comment by lxa9867** [comment]
There is something interesting about this, we will try to discuss this in a later update to the preprint (may not be next time as we will first update the main results and the updating will last for about 1 month we estimated).

**Comment by HalvesChen** [comment]
Hi~ Could you provide detailed training details, such as epoch, dataset, codebook dimension, etc.

**Comment by lxa9867** [comment]
More details will be added in the next version. Please stay tuned.

As discussed in the preprint, we generally follow the LlamaGen training recipe and make slight changes.

**Comment by lxa9867** [comment]
code released, closing this issue.
