### ISSUE TITLE
About main fun of discriminator_dino

### ISSUE THREAD

**Issue by HalvesChen** [lxa9867/ImageFolder#10]
Hi~ Thanks for your great work.
I have some problem about discriminator_dino, When I run the main fun of discriminator_dino, I get different results from you provide.
I get:
mean: [0.019, -0.028, 0.054, 0.058, 0.074]
std: [0.427, 0.142, 0.169, 0.194, 0.153]
o: 17928.818359375, 27946.619140625
I use V100 to run the code, Is there a problem here？

**Comment by lxa9867** [comment]
Hi,

Thanks for your interest. I don’t quite understand your question. Could you provide more descriptions about the problem?

**Comment by HalvesChen** [comment]
I run the command `python discriminator_dino.py` to test if the results I get are normal, but the results I get are：
mean: [0.019, -0.028, 0.054, 0.058, 0.074]
std: [0.427, 0.142, 0.169, 0.194, 0.153]
o: 17928.818359375, 27946.619140625.
This is very different from the results provided in the discriminator_dino.py:
"""
对于使用qkv的版本，输出是
7.39M
mean: [0.019, -0.028, 0.054, 0.058, 0.074]
std: [0.427, 0.142, 0.169, 0.194, 0.153]
o: 50.266475677, 91.698143005.

**Comment by lxa9867** [comment]
Hi,

We didn’t use the direct run discriminator_dino.py to test the code. But V100 should not be a problem. Please let me know if you think there is something wrong. Thanks.

**Comment by HalvesChen** [comment]
Hi, 
could you run discriminator_dino.py in your conda environment to see the results? In fact, I'm not sure whether the difference in results will affect training.

**Comment by qiuk2** [comment]
Hi, thanks for your interest in our XQGAN, I run the above cmd and got the result 
mean: [0.019, -0.028, 0.054, 0.058, 0.074]
std: [0.427, 0.142, 0.169, 0.194, 0.153]
o: 17928.820312500, 27946.615234375
