### ISSUE TITLE
Inspiring work, looking forward to the release of code and checkpoints!

### ISSUE THREAD

**Issue by iamlockelightning** [lxa9867/ImageFolder#2]
Inspiring work, looking forward to the release of code and checkpoints! Is there an approximate release time?

**Comment by lxa9867** [comment]
Thanks for your interest!

We are working on the long training of the ImageFolder tokenizer and the final performance should be 1.xx gFID🚀. We have submitted the code-releasing request to the company, I would expect it will be available in about one month.

**Comment by lxa9867** [comment]
code released, closing this issue.
