### ISSUE TITLE
About results in Table 4

### ISSUE THREAD

**Issue by krennic999** [lxa9867/ImageFolder#3]
Hello, your work is really great and has inspired me deeply. I would like to ask how you selected imagenet50k in the imagenet rFID in table 4 and how to convert it to 256 resolution. Thanks a lot!

**Comment by lxa9867** [comment]
Hi,

Thanks for your interest. We used the implementation from LlamaGen.

**Comment by krennic999** [comment]
Thanks, it does help a lot!

**Comment by lxa9867** [comment]
code released, closing this issue.
