### ISSUE TITLE
Why total token numer is 265?

### ISSUE THREAD

**Issue by Changlin-Lee** [lxa9867/ImageFolder#5]
Hi, thanks for the good work!
In my understanding of the original VAR quantizer, they use [1,2,3,4,5,6,8,10,13,16] as v_patch_num, results 1+4+9+16+25+36+64+100+169+256=680 tokens.

However, in my understanding of the paper, the v_patch_num is set as [1, 1, 2, 3, 3, 4, 5, 6, 8, 11], results 2*(1+1+4+9+9+16+25+36+64+121)=286*2 =572 tokens(as we have two vq branches?) 

How the 265 tokens is calculated in the paper?

Thanks

**Comment by lxa9867** [comment]
Hi ChangLin,

Thanks for your interest. Yes, the token length for this version should be 286. We forgot to update the length in the table and the 265 is resulted from a last scale of 10x10.

We will update the arxiv shortly with the released code link and new results. Thank you again for raising this up.

**Comment by Changlin-Lee** [comment]
Hi,

Thanks for the reply. By the way, as mentioned above, we have two VQ branches. Thus, the AR model actually takes 286*2 tokens, is that right?

**Comment by lxa9867** [comment]
Yes, this is right.

**Comment by Changlin-Lee** [comment]
Get it. Thanks for your great work, looking for the code being released soon.
