### ISSUE TITLE
ModuleNotFoundError: No module named 'tokenizer.tokenizer_image.sam'

### ISSUE THREAD

**Issue by zhouxingguang** [lxa9867/ImageFolder#7]
vq_model = VQ_models['VQ-16'](
        codebook_size=16384,
        codebook_embed_dim=8,
        commit_loss_beta=0.25,
        entropy_loss_ratio=0.0,
        dropout_p=0.0,
        v_patch_nums=[1, 2, 3, 4, 5, 6, 8, 10, 13, 16],
        enc_type="cnn",
        encoder_model='vit_small_patch14_dinov2.lvd142m',
        dec_type="cnn",
        decoder_model='vit_small_patch14_dinov2.lvd142m',
        semantic_guide="dinov2",
        num_latent_tokens=256,
        abs_pos_embed=False,
        share_quant_resi=4,
        product_quant=1,
        codebook_drop=0.0,
        half_sem=False,
        start_drop=1,
        sem_loss_weight=0.1,
        clip_norm=False,
        sem_loss_scale=1.0,
    )

![image](https://github.com/user-attachments/assets/33f967f2-cd32-4652-93f6-134fce5d9ef8)

**Comment by lxa9867** [comment]
Hi,

Can you please pull the repo again and try? There are some functions that haven't been supported in the latest version.

**Comment by zhouxingguang** [comment]
the problem not solve, can you give a example to how to use the vq_model to encoder image and reconstruct the image?

**Comment by lxa9867** [comment]
Hi, your config looks good. Can you please show the errors after you pulled the repo? I think there is no msvq_model.py in the updated repo. Thanks.
